import Navbar from '@/components/navbar/Navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import WhoWeAre from '@/components/whoweare/WhoWeAre'
import OurServices from '@/components/ourservices/OurServices'
import WhatWeDo from '@/components/whatwedo/WhatWeDo'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children,}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar></Navbar>
        {children}
        <WhoWeAre></WhoWeAre>
        <OurServices></OurServices>
        <WhatWeDo></WhatWeDo>
        </body>
    </html>
  )
}
